parameters:
- name: helmVersion
  displayName: Helm Version
  type: string

steps:
- task: HelmInstaller@1
  displayName: 'Install Helm (${{ parameters.helmVersion }})'
  inputs:
    helmVersionToInstall: '${{ parameters.helmVersion }}'