parameters:
- name: chartName
  displayName: Helm Chart Name
  type: string
- name: chartVersion
  displayName: Helm Chart Version
  type: string
- name: chartLocation
  displayName: Helm Chart Location
  type: string
- name: registryName
  displayName: Azure Container Registry Name
  type: string
- name: registrySubscription
  displayName: Subscription Name of Azure Container Registry
  type: string
- name: workingDir
  displayName: Working Directory
  type: string
  default: 'dir'


steps:
- task: AzureCLI@2
  displayName: 'Push ''${{ parameters.chartName }}'' Helm chart v${{ parameters.chartVersion }} to registry'
  inputs:
    azureSubscription: '${{ parameters.registrySubscription }}'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az configure --defaults acr=${{ parameters.registryName }}
      az acr helm push --name ${{ parameters.registryName }} ${{ parameters.chartLocation }}/${{ parameters.chartName }}-${{ parameters.chartVersion }}.tgz --force
    workingDirectory: '${{ parameters.workingDir }}'