parameters:
- name: registryName
  displayName: Azure Container Registry Name
  type: string
- name: serviceConnectionName
  displayName: Azure Service Connection Name
  type: string

steps:
- task: AzureCLI@2
  displayName: Setup ${{ parameters.registryName }} Helm repo
  inputs:
    azureSubscription: '${{ parameters.serviceConnectionName }}'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az configure --defaults acr=${{ parameters.registryName }}

      echo 'Adding repo'
      az acr helm repo add --name ${{ parameters.registryName }}
- template: ./update-repo.yml
- template: ./list-available-charts.yml
  parameters:
    repositoryName: '${{ parameters.registryName }}'